# Branches to build
branches:
  only:
  - master

# Start builds on tags only
skip_non_tags: true

# Skipping commits
skip_commits:
  files:
  - README.md

# Maximum number of concurrent jobs for the project
max_jobs: 1

# Build cache to preserve files/folders between builds
cache: c:\lazarus -> appveyor-install.cmd

# Scripts that run after cloning repository
install:
  - cmd: appveyor-install.cmd

# Build scripts
build_script:
  - cmd: appveyor-build.cmd

# Scripts to run after build
after_build:
  - cmd: 7z a -tzip pasdivert-win32.zip .\fpc\Win32\Release\*.exe .\x86\*.dll .\x86\*.sys README.md LICENSE
  - cmd: 7z a -tzip pasdivert-win64.zip .\fpc\Win64\Release\*.exe .\amd64\*.dll .\amd64\*.sys README.md LICENSE

# Artifacts configuration
artifacts:
  # pushing all *.zip files in build directory recursively
  - path: '**\*.zip'

# Deployment configuration
deploy:
  provider: GitHub
  auth_token:
    secure: "eU0j66hTsR4ou10kFzDoXFNj1495/CRz56XtLroAcOIGvCm407/hpffOQmswsd1W"
  artifact: /.*\.zip/              # upload all zip packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
